import Sidebar from "./components/Sidebar";
import "./globals.css";
import { Genos } from "next/font/google";

const genos = Genos({
  variable: "--font-genos",
  subsets: ["latin"],
  weight: "400", // only available weight
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${genos.variable} antialiased genos flex flex-row bg-[#FFEFD7]`}
      >
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
