import "./globals.css";
import { Genos } from "next/font/google";
import AuthLayout from "./components/AuthLayout";

const genos = Genos({
  variable: "--font-genos",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${genos.variable} antialiased genos bg-[#FFEFD7]`}>
        <AuthLayout>{children}</AuthLayout>
      </body>
    </html>
  );
}
