import "./globals.css";
import { Capriola } from "next/font/google";

const capriola = Capriola({
  variable: "--font-capriola",
  subsets: ["latin"],
  weight: "400", // only available weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${capriola.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
